services:
  postgres:
    container_name: db
    image: postgres:18.3-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: meow
      POSTGRES_PASSWORD: UwU
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./source_data:/docker-entrypoint-initdb.d
    networks:
      - meowork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meow -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  broker:
    image: apache/kafka:4.2.0
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 10
    networks:
      - meowork
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8085:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - broker
    networks:
      - meowork

  flink-loader:
      image: alpine:3.21
      container_name: flink_loader
      volumes:
        - flink_libs:/libs
      command: >
        sh -c "apk add --no-cache wget &&
              wget -P /libs/ https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/4.0.1-2.0/flink-sql-connector-kafka-4.0.1-2.0.jar &&
              wget -P /libs/ https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc-core/4.0.0-2.0/flink-connector-jdbc-core-4.0.0-2.0.jar &&
              wget -P /libs/ https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc-postgres/4.0.0-2.0/flink-connector-jdbc-postgres-4.0.0-2.0.jar &&
              wget -P /libs/ https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar"
      networks:
        - meowork

  jobmanager:
    image: flink:2.2.0-java17
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - flink_libs:/opt/flink/lib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "http://localhost:8081/overview"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      flink-loader:
        condition: service_completed_successfully
    networks:
      - meowork

  taskmanager:
    image: flink:2.2.0-java17
    container_name: taskmanager
    command: taskmanager
    volumes:
      - flink_libs:/opt/flink/lib
    environment:
          FLINK_PROPERTIES: |
            jobmanager.rpc.address: jobmanager
            taskmanager.numberOfTaskSlots: 10
            taskmanager.memory.process.size: 1600m
    depends_on:
      jobmanager:
        condition: service_healthy
    networks:
      - meowork

  flink-job:
    image: flink:2.2.0-java17
    container_name: flink_job
    command: >
      sh -c "sleep 5 &&
             /opt/flink/bin/sql-client.sh --file /flink/job.sql"
    volumes:
      - flink_libs:/opt/flink/lib
      - ./flink:/flink:ro
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    depends_on:
      flink-loader:
        condition: service_completed_successfully
      jobmanager:
        condition: service_started
      taskmanager:
        condition: service_started
      broker:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - meowork
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/job_ready"]
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 45s

  producer:
        image: ghcr.io/userver-framework/ubuntu-24.04-userver:latest
        privileged: true
        environment:
            - CCACHE_DIR=/producer/.ccache
            - CMAKE_OPTIONS
            - CORES_DIR=/cores
            # - SECDIST_CONFIG={"kafka_settings":{"kafka-producer":{"brokers":"broker:9092"}}}
        volumes:
          - ./producer:/producer:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
          - ./source_data:/data:ro
          - ./producer/configs/secure_data.json:/etc/producer/secure_data.json:ro
          - ./producer/configs/static_config.yaml:/etc/producer/static_config.yaml:ro
          - ./producer/configs/config_vars.yaml:/etc/producer/config_vars.yaml:ro
        ports:
          - 8052:8052
        working_dir: /producer
        command: >
                    bash -c "
                        cd /producer &&
                        mkdir -p build && cd build &&
                        cmake .. -DCMAKE_BUILD_TYPE=Release ${CMAKE_OPTIONS} &&
                        make -j$$(nproc) &&
                        /producer/build/producer --config /etc/producer/static_config.yaml
                    "
        depends_on:
          broker:
            condition: service_healthy
          flink-job:
            condition: service_healthy
        networks:
        - meowork

networks:
  meowork:
    driver: bridge

volumes:
  postgres_data:
  flink_libs:
