config_vars: /etc/producer/config_vars.yaml

components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads
        producer-task-processor:
            thread_name: producer
            worker_threads: 4
        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor
                connection:
                    in_buffer_size: 32768
                    requests_queue_size_threshold: 100
            listener-monitor:
                port: $monitor-server-port
                port#fallback: 8086
                connection:
                    in_buffer_size: 32768
                    requests_queue_size_threshold: 100
                task_processor: monitor-task-processor
            logger_access: ''
            logger_access_tskv: ''
            max_response_size_in_flight: 1000000000
            server-name: $server-name

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    format: json
                    # file_path: '@stdout'
                    file_path: './logs/producer.log'
                    level: $logger-level
                    overflow_behavior: discard

        dynamic-config:
            defaults: {}

        default-secdist-provider:
            config: /etc/producer/secure_data.json
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        secdist: {}

        kafka-producer:
            delivery_timeout: 10s
            queue_buffering_max: 100ms
            enable_idempotence: true  
            security_protocol: PLAINTEXT

        handler-inspect-requests:
            path: /service/inspect-requests
            method: GET
            task_processor: monitor-task-processor
        handler-jemalloc:
            path: /service/jemalloc/prof/{command}
            method: POST
            task_processor: monitor-task-processor
        handler-log-level:
            path: /service/log-level/{level}
            method: GET,PUT
            task_processor: monitor-task-processor
        handler-on-log-rotate:
            path: /service/on-log-rotate/
            method: POST
            task_processor: monitor-task-processor
        handler-dynamic-debug-log:
            path: /service/log/dynamic-debug
            method: GET,PUT,DELETE
            task_processor: monitor-task-processor
        handler-dns-client-control:
            path: /service/dnsclient/{command}
            method: POST
            task_processor: monitor-task-processor
        handler-server-monitor:
            path: /service/monitor
            method: GET
            task_processor: monitor-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        csv-producer:
            csv-dir: $csv-dir
            topic: $kafka-topic
            batch-size: 100

