config_vars: /etc/producer/config_vars.yaml

components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads
        producer-task-processor:
            thread_name: producer
            worker_threads: 4
        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        dynamic-config:
            defaults: {}

        default-secdist-provider:
            config: /etc/producer/secure_data.json
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        secdist: {}

        kafka-producer:
            delivery_timeout: 10s
            queue_buffering_max: 100ms
            enable_idempotence: true  
            security_protocol: PLAINTEXT

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor

        csv-producer:
            csv-dir: /data
            topic: input-topic
            batch-size: 100

